# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jisokang <jisokang@student.42seoul.kr>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/08/22 17:31:21 by jisokang          #+#    #+#              #
#    Updated: 2021/10/08 01:35:12 by jisokang         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC		= gcc
CFLAGS	= -Wall -Werror -Wextra
SRCS	= philo.c routine.c util.c init.c thread.c philo.h color.h

all :
	$(CC) $(CFLAGS) $(SRCS)
